version: '3.7'
services:
  homeless-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: homeless

  homeless-backend:
    container_name: homeless-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8888:80'
    depends_on:
      - 'homeless-mysql'